### ISSUE TITLE
Cookbook generate repo config without baseurl

### ISSUE THREAD

**Issue by UnderGreen** [chef-cookbooks/yum-mysql-community#7] opened 2015-12-01 10:38 UTC
Hi, 
With version 0.1.20 of cookbook on Centos 7 repo file is:
```ini
# This file was generated by Chef
# Do NOT modify this file by hand.

[mysql55-community]
name=MySQL 5.5 Community Server
enabled=1
failovermethod=priority
gpgcheck=1
```
I think problem in code `baseurl node['yum']['mysql55-community']['baseurl'] if  node['yum']['mysql55-community']['baseurl'].nil?`. Maybe in this place should be `unless`?

Addition information about system:
```
knife node show chef12-client.test -l | grep -E '^platform'
platform:          centos
platform_family:   rhel
platform_version:  7.1.1503
```

**Comment by someara** [comment] 2015-12-02 06:14
should be fixed up in the latest release
-s

**Closed by someara** 2015-12-02 06:14 UTC

**Comment by eric-tucker** [comment] 2015-12-03 12:44
The problem is that one cannot have a successful Chef run after having 0.1.20 unleashed on their servers as the broken yum repo prevents the Chef run from getting to the point where the updated cookbook fixes the repo file (unless you happen to have no yum calls before getting to this cookbook).

So anyone who encounters this issue, you have to manually remove the broken repo file before running Chef to fix the issue.

I'm surprised this wasn't caught in testing.  It is trivial to reproduce using cookbook version 0.1.20.  Just set your cookbook dependency to this version and run Chef. Things immediately blow up when yum tries to refresh cache based on the new/updated repo file.
